
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
      - /app/node_modules
    env_file:
      - ./front/.env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
